### ISSUE TITLE
Table sorting is not keyboard accessible

### ISSUE THREAD

**Issue by patrickhlauke** [phuoc-ng/html-dom#104]
Adding `click` handler to the `<th>` elements won't allow keyboard users to activate the sort functionality https://htmldom.dev/sort-a-table-by-clicking-its-headers

You'll likely want to use some actual `<button>` elements - need to be keyboard-focusable, respond to SPACE, and expose an appropriate button role in any case.

**Comment by phuoc-ng** [comment]
Thanks @patrickhlauke for the suggestions.
I saw another your feedbacks as well, and I'll pay more attention on supporting accessibility!

**Comment by patrickhlauke** [comment]
thank you. no worries, it's often easily overlooked. it's still a wonderful collection you've put together here, overall!
