### ISSUE TITLE
Dear phuoc, can I get editing rights for the html-dom Chinese site?

### ISSUE THREAD

**Issue by PLQin** [phuoc-ng/html-dom#119]
if you permit us ,
I will purchase the relevant domain name and server at my own expense.
And retain your copyright and authorship,
Keep the hyperlink to https://htmldom.dev/ prominently on the site

**Comment by PLQin** [comment]
@phuoc-ng looking forward to your reply

**Comment by Technetium1** [comment]
@phuoc-ng I think it should be possible to have a dropdown at the top of htmldom.dev to change the language. Maybe a _sub_ domain specifically for Chinese? This seems to be hosted with Netlify so here's [a help article for Netlify DNS](https://docs.netlify.com/domains-https/custom-domains/#definitions). Maybe `/chinese` is a possibility? Technically you may host and modify this content elsewhere @PLQin, but you must always follow [the license](https://github.com/phuoc-ng/html-dom/blob/51e42fb1823ef6c3232fd257c3af45c2e9535247/LICENSE#L1) closely (:

**Comment by phuoc-ng** [comment]
I prefer to keep all the translated versions in a single site. The user can change the language once or see the post in another language when reading a particular post.

It will keep the content up-to-date together.
To support that, I have to prepare some stuffs first. I'll create another issue to track that.

cc @XHH97

**Comment by PLQin** [comment]
> I prefer to keep all the translated versions in a single site. The user can change the language once or see the post in another language when reading a particular post.
> 
> It will keep the content up-to-date together.
> To support that, I have to prepare some stuffs first. I'll create another issue to track that.
> 
> cc @XHH97

But China is a bit of a special case because of GWF, a significant number of programmers can't access sites deployed outside of China

**Comment by rkben** [comment]
> > I prefer to keep all the translated versions in a single site. The user can change the language once or see the post in another language when reading a particular post.
> > It will keep the content up-to-date together.
> > To support that, I have to prepare some stuffs first. I'll create another issue to track that.
> > cc @XHH97
> 
> But China is a bit of a special case because of GWF, a significant number of programmers can't access sites deployed outside of China

It makes more sense for your translations to go reach upstream (here) and you to just mirror the site @PLQin this adds the benefit of your mirror (within the GWF) having the other translations available. The license is MIT so mirroring shouldn't be an issue, unless i missed an image or icon that is licensed differently.
