### ISSUE TITLE
There was an error with the copy:demo command

### ISSUE THREAD

**Issue by XHH97** [phuoc-ng/html-dom#132]
The SET error disappears。
![image](https://user-images.githubusercontent.com/25319143/78352369-ccf2b580-75da-11ea-819c-3f8ae860b7da.png)

**Comment by elkarouani** [comment]
Try again using npm command

**Comment by XHH97** [comment]
The WSL win10

**Comment by elkarouani** [comment]
I think the problem is that the command set doesn't work on unix-like terminals, but it works on windows cmd, can you test the same command on git bash ?

**Comment by XHH97** [comment]
Problem solved, thanks

**Comment by elkarouani** [comment]
Can you say what is your solution ?

**Comment by XHH97** [comment]
Use the git bash way you said, which you had previously ignored
